CREATE TABLE cursos (
    id CHAR(36) NOT NULL DEFAULT(UUID()),
    nome VARCHAR(255) NOT NULL,
    categoria VARCHAR(100),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    data_exclusao TIMESTAMP NULL,
    PRIMARY KEY (id)
);
