### Criar novo usuário - é necessário estar logado como ADMIN

# @name criarUsuario

POST {{API_URL}}/usuarios HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "cargo": "ADMIN",
  "email": "teste2@gmail.com",
  "nome": "Teste 3",
  "senha": "@Teste12345"
}


### Listar usuários - é necessário estar logado como ADMIN

# @name listarUsuarios

GET {{API_URL}}/usuarios HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}


### Buscar usuário por ID - é necessário estar logado como ADMIN

# @name buscarUsuarioPorId

GET {{API_URL}}/usuarios/6ea4cdcb-89f3-4ffc-b700-e013008ac4e3 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}


### Atualizar usuário - é necessário estar logado como ADMIN

# @name atualizarUsuario

PATCH {{API_URL}}/usuarios/6ea4cdcb-89f3-4ffc-b700-e013008ac4e3 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "ativo": false,
  "cargo": "ADMIN",
  "email": "teste5@gmail.com",
  "nome": "Teste 3 Atualizado"
}


### Deletar usuário - é necessário estar logado como ADMIN

# @name deletarUsuario

DELETE {{API_URL}}/usuarios/d03fad8c-bdfc-4a24-8793-65845b62cb8c HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}
